### ISSUE TITLE
Documentation: Usage in CI

### ISSUE THREAD

**Issue by Eorhim** [eea/eea.docker.pylint#1]
Having an example in the Travis CI section would be helpful.

Here my working example for the GitLab CI:

```yaml
pylint:
  script:
    - pylint --rcfile=$CI_PROJECT_DIR/.pylint $CI_PROJECT_DIR
  image: eeacms/pylint
  stage: lint
```
